# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-13 20:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billboardapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='text_comment',
            new_name='texts_comment',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='text',
            new_name='texts',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='lastupdate_date',
        ),
    ]
