# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-13 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billboardapp', '0002_auto_20190113_2247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='texts_comment',
            new_name='text_comment',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='texts',
            new_name='text',
        ),
    ]
